---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: snykly
    app.kubernetes.io/name: snykly
    app.kubernetes.io/version: "1.0"
  name: snykly
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: snykly
    app.kubernetes.io/name: snykly
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snykly
  labels:
    app.kubernetes.io/instance: snykly
    app.kubernetes.io/name: snykly
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
        app.kubernetes.io/instance: snykly
        app.kubernetes.io/name: snykly
  template:
    metadata:
      labels: 
        app.kubernetes.io/instance: snykly
        app.kubernetes.io/name: snykly
    spec:
      containers:
        - name: snykly
          image: garethr/snykly
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
