name: Snyk
on:
  push:
  workflow_dispatch:
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
      with:
        snyk-version: v1.391.0
    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - name: Snyk version
      run: snyk version
    - name: Snyk monitor 
      run: snyk monitor --project-name=garethr/snykly
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
